- app/lol/connector.py
修复 #30 
当要观战的玩家不在游戏时，抛出一个 `SummonerGamesNotFound` 异常
> [Bugfix] Optimize spectate() behaviour

- make.ps1
> fix make script redundant -r

- .github/workflows/build_seraphine.yaml
修复了 Github Actions 的非预期行为。
1. 当且仅当修改 `app/common/config.py` 下的 VERSION 变量时，才下载产物，并推送到 Release。
- 通过正则匹配 git blame 获取 VERSION = "x.x.x" 行的修改 commit 的 sha 值。
- 通过正则匹配 git log 获取 HEAD commit 的 sha 值。
- 比较两者，当两者相同时，证明该 commit 修改了版本号，需要触发后续操作；否则跳过后续操作。
- 触发下载产物和推送到 Release
2. 添加 `replacesArtifacts: false`，不允许新生成的产物覆盖旧产物。
这次应该是 ok 了~
> [Github Actions] Fix Github Actions

- app/components/summoner_name_button.py
- app/view/main_window.py
- app/view/setting_interface.py
#44 
作为 pyqt-fluent-widgets 修复前的临时措施
> 临时修复最小化到托盘时, 右键菜单位置不正确的BUG

- app/view/game_info_interface.py
- app/view/main_window.py
1. 修复对局开始后再打开软件"对局信息"页会显示为空 #53 
2. 降低"对局信息"页, 召唤师图标更新频率(仅差异时触发图标更新) 
https://github.com/Zzaphkiel/Seraphine/blob/e86545a2ff2849510bff65e9a6e8622a528e54d7/app/view/main_window.py#L706C1-L706C1
3. 添加"游戏中"状态自动跳转到"对局信息"页
4. "对局信息"页的自动跳转改为渲染完成后触发
> 对局信息相关修复和改动

- app/components/mode_filter_widget.py
- app/components/profile_level_icon_widget.py
- app/lol/tools.py
- app/view/game_info_interface.py
- app/view/search_interface.py
1. [修复进入大乱斗后再打开软件报错问题](https://github.com/Zzaphkiel/Seraphine/commit/b9ad54caf30fb8d6029b629100d19b087b24de7a) 
相关Issues: 
https://github.com/Zzaphkiel/Seraphine/issues/53#issuecomment-1722412637
2. 战绩查询添加筛选功能
3. 重构历史战绩拉取逻辑
TODO 本地化:  详情可见代码内TODO
> 战绩查询功能新增筛选, 修复进入大乱斗后再打开软件报错问题

- app/lol/connector.py
- app/view/search_interface.py
目前推测是由于异步加载战绩导致其余战绩获取的请求无法被及时响应, 影响了以下功能:
1. 对局信息(获取历史战绩时)
2. 个人主页(获取历史战绩时)
该pr降低了战绩查询时异步获取数据的步长, 并将接口改为可被抢断的以保证其他功能的请求能够被及时响应
> 修复执行战绩查询操作后, 其他功能受到影响的BUG

- app/components/profile_level_icon_widget.py
> BUG修复: 经验条可能为空的BUG

- app/common/config.py
- app/lol/connector.py
- app/lol/listener.py
BUG修复: 请求量过大时导致的LCU客户端闪退, 最大并发数改为2 #158
BUG修复: "显示对局数"过高导致的LCU API拒绝请求, 该选项的上限值设置为60 #170
易用性: 为检测LCU启动的未知错误添加了异常抛出, 再次遇到时可以具体定位问题 #174
> bugfix #158 #170

- .gitignore
- app/components/profile_level_icon_widget.py
修复 #74 的报错问题。
当使用 python 3.11 通过源码运行 seraphine 时，会报错 `QPaintDevice: Cannot destroy paint device that is being painted`。
因为 `app/components/profile_level_icon_widget.py` 中的 `RoundLevelAvatar.paintEvent()` 函数内有两处函数调用的参数类型有误，参数的期望类型是 int，但是输入的 `self.sep` 和 `self.sep // 2` 是 float 类型的，所以引发错误。解决方法就是显式转换成 int 类型。
修复后，通过源码运行，软件行为正常。
此外，在 .gitignore 文件中，忽略 `venv/` 和 `seraphine/`。
> [bugfix] Fix profile_level_icon_widget paintEvent

- app/view/main_window.py
- app/view/search_interface.py
1. 修复战绩筛选时, 若一个人从未打过被筛选的模式, 会keyError的bug
2. 修复加载战绩详情时, 如果频繁切换查询的场次, 会导致await self.updateGameDetailView(tab.gameId)积压, 加载时间很长, 并且直到最终全部加载完成后才会一次连续更新很多场(每场一闪而过)
> BUG FIX : 战绩查询相关BUG

- app/components/SeraphineInterface.py
- app/lol/connector.py
- app/lol/exceptions.py
- app/lol/tools.py
- app/view/auxiliary_interface.py
- app/view/career_interface.py
- app/view/game_info_interface.py
- app/view/main_window.py
- app/view/search_interface.py
- app/view/setting_interface.py
- app/view/start_interface.py
1. 修复弱网条件下, rank信息获取异常导致的各种问题 (重要) #301
2. 修复了战绩查询时, 频繁切换查询的召唤师会导致此前的查询任务仍在进行的BUG (重要, 效率影响巨大)
3. 优化了生涯页的加载速度
> BUG FIX: 弱网下Rank信息获取出错; 战绩查询逻辑导致效率问题; 生涯页加载速度; 添加崩溃时InterfaceLog

- app/view/search_interface.py
> BUG FIX: 修复战绩查询时, 只会加载前两页的BUG

- app/view/main_window.py
- app/view/search_interface.py
1. 修复战绩查询时, 偶尔会出现重复战绩的BUG
2. 修复战绩查询时, 模式筛选需要等待全部战绩加载完成的BUG
3. 修复生涯页快速切换到战绩查询页并且换人时, 出现AttributeError的BUG
> BUG FIX: 战绩查询相关问题

- app/common/config.py
- app/lol/tools.py
- app/view/auxiliary_interface.py
1. 杜绝getSummonerGamesByPuuid和getRankedStatsByPuuid经常报错
2. 解析异常的召唤师信息提供显示一个默认模板（人机队友、报错后现在可以显示一个占位卡片）
3. 修复排位过滤问题（#161）
> fix/break change(#161): 重写解析召唤师信息逻辑

- app/components/profile_level_icon_widget.py
- app/view/main_window.py
- app/view/setting_interface.py
1. 修复大乱斗buff卡片会受到主窗口大小限制显示不全; 
2. 移除了"游戏开始时最小化Seraphine"的设置选项以及功能
> bugfix: 修复大乱斗buff卡片会受到主窗口大小限制显示不全; 移除了"游戏开始时最小化Seraphine"的设置选项以及功能

- app/components/search_line_edit.py
- app/lol/connector.py
- app/view/search_interface.py
1. FIX 连续在候选栏选中两次相同召唤师会起两个task同时加载导致客户端闪退
2. FIX 使用cancel()有时候无法终止task
3. 优化战绩搜索UI响应速度
> FIX: 特定条件下, 战绩查询会干掉客户端

- app/common/util.py
printing the original error may be helpful for
troubleshooting issues like #456 and #367.
> optimize: print original error if 'tasklist' fails

- app/lol/connector.py
- app/view/auxiliary_interface.py
客户端现在支持云顶之弈观战，此方法暂不支持（没去找，加个把参数的事）。
原来的接口方式可能需要保留，加个按钮？
爱来自[https://github.com/Ninohana/lol](https://github.com/Ninohana/lol)
> Fix(观战): 现在观战功能无需再等待

- app/view/opgg_window.py
https://github.com/Zzaphkiel/Seraphine/blob/99c5ff9a175c8571bafe974e4274e856be200d27/app/view/opgg_window.py#L502
The previous fix (https://github.com/Zzaphkiel/Seraphine/pull/544/commits/20f1e24439f0fa310695c5c9362fbbe596fcb477) is a stupid mistake, fixed it again...
> fix bug in opgg_window again
