Zzaphkiel/Seraphine

app/lol/connector.py, app/view/auxiliary_interface.py, app/view/main_window.py
=> 完成了自动选择英雄的功能

app/view/main_window.py
1. 修复因测试使用自定义模式漏测导致的闪退问题
2. 检查预组队时改为并发, 大幅降低页面加载时间
=> 修复进游戏报错, 改并发

app/view/main_window.py
=> 修复对局开始后再打开软件报错

app/view/main_window.py
=> 修复当敌方阵容中有AI玩家时报错的BUG

app/lol/connector.py, app/view/main_window.py, app/view/search_interface.py
1. bug修复: 进入游戏后再打开软件, "对局信息"的队友部分不会显示预组队信息
3. bug修复: 进入游戏后再打开软件, 如果存在某位召唤师在最近11局游戏内不少于n次排到当前某位队友的敌对方时, 会导致程序出错, KeyError (n为预组队阈值)
=> BUG修复 (现版本所有已暴露的阻断性质BUG)

app/components/summoner_name_button.py, app/lol/entries.py, app/lol/tools.py, app/view/career_interface.py, app/view/game_info_interface.py, app/view/main_window.py, app/view/search_interface.py
=> 功能更新: 实现了隐藏战绩的召唤师标记

app/common/logger.py, app/components/profile_level_icon_widget.py, app/lol/listener.py, app/view/career_interface.py, app/view/main_window.py
1. 修复bp切换选择的英雄时, Seraphine界面更新存在延迟的问题
2. 修复更换召唤师头像时, Seraphine界面更新存在延迟的问题
3. 添加listener模块log
=> Bugfix 头像更新延迟

app/common/config.py, app/lol/connector.py, app/view/auxiliary_interface.py, app/view/main_window.py
在autoBP分支下，实在弄不来Qt界面，只把ban英雄的代码实现了
=> 新增自动ban亚索的功能（😋) issue#175

app/common/config.py
Move Seraphine config to `%APPDATA%` on Windows so that it can be kept when Seraphine updates.
=> [Refactor] Move Seraphine config to user directory

app/common/config.py, app/lol/connector.py, app/lol/tools.py, app/view/auxiliary_interface.py, app/view/career_interface.py, app/view/game_info_interface.py
1. 添加自动Ban人的延迟功能
3. 添加自动选用时, 若保持亮起但未锁定, 超时前将英雄锁定的功能
4. 修复位于房间内, 打开软件会报错的BUG
5. 修复查询召唤师时如果查无此人, 会反复报错的BUG
6. LcuWebSocket改为一个event可以同时支持多个subscribe(此前是匹配上了就返回)
7. LcuWebSocket的subscribe注册时, 若不传入uri或type, 则匹配任何event
TODO 本地化
=> bp功能完善、bug修复

.github/workflows/build_seraphine.yaml, sync.py
use `sync.py` to sync latest Seraphine release to Gitee Release.
=> [Github Actions] add a script to sync release

app/lol/connector.py, app/lol/tools.py, app/view/main_window.py
fix: 预选阶段无法选择英雄（#283）
feat: 自动接受楼层或英雄的交换请求（界面未实现）
=> bug修复与功能新增

app/lol/connector.py, app/lol/tools.py, app/view/main_window.py
- 修复了锁定选用的bug
> 该bug会导致：选人阶段中途有人退出，获取信息会报错。并且更换了位置后，无法很好地工作。
- 优化了auto处理逻辑，现在会以冒泡方式工作，有更良好的性能表现（待观察）
- 新增auto组件，可以在皮肤多不知道玩哪个是随机帮你选一个
=> bug修复、性能优化与功能新增

app/lol/connector.py, app/view/main_window.py
1. crash时在log中记录最近10次connector请求
2. 一些结构调整
3. 一处未等待的协程
=> 功能更新: 在crash时记录最近的connector调用, 关于py协程的注释

app/view/game_info_interface.py, app/view/main_window.py
修复艾欧尼亚对局信息不包含编号导致从对局信息跳转历史战绩时查询失败的问题
=> 修复艾欧尼亚对局信息不包含编号导致从对局信息跳转历史战绩时查询失败的问题

app/common/util.py, app/view/auxiliary_interface.py, app/view/main_window.py
1. 修复锁定config文件可能导致栈溢出的BUG
2. 当游戏路径为空时, 尝试从注册表读取当前的安装路径
=> bugfix & perf 

app/lol/connector.py
503 Service Temporarily Unavailable
=> fix(SGP): 移除已经过时的服务器

app/components/champion_icon_widget.py, app/components/message_box.py, app/lol/connector.py, app/view/auxiliary_interface.py
1. 在选择生涯背景时提供预览
2. 在选择生涯背景时, 可以将原画保存到本地
https://github.com/user-attachments/assets/32d39f51-4632-41d2-bd68-3860f15b81c4
=> 在选择生涯背景时提供预览

app/lol/champions.py, app/view/main_window.py, app/view/opgg_window.py
=> fix: 云母效果与子窗口不统一

app/common/style_sheet.py
=> fix: add type conversion to fix wrong argument type

app/view/career_interface.py
发现直接进入生涯页面不会显示KDA计算结果，故作此修改（ ~~顺便格式化了两行代码~~
=> 修复个人生涯页面KDA计算结果仅在部分情况下显示的问题(Bug?Feature?)

app/lol/connector.py, app/view/auxiliary_interface.py
> 爱来自[Ninohana/lcu](https://github.com/Ninohana/lcu)
=> feat: #599
